apiVersion: v1
data:
  var5: val5
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-17T13:56:44Z"
  name: options
  namespace: default
  resourceVersion: "935192"
  selfLink: /api/v1/namespaces/default/configmaps/options
  uid: 4546a20d-54af-47e8-9b51-c6c66dad015e
