apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crone-job
spec:
  schedule: "1/2 * * * *"
  jobTemplate:
    spec:
      completions: 2
      parallelism: 2
      template:
        spec:
          containers:
            - name: centos
              image: centos
              command: ['yum', 'update']
              args: ['uname']
          restartPolicy: Never