apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: aziz
  labels:
    app: qwerty
spec:
  template:
    metadata:
      name: aziz-pod
      labels:
        app: qwerty
    spec:
      containers:
        - name: nginx
          image: nginx
          envFrom:
            - configMapRef:
                name: appcolor
  selector:
    matchLabels:
      app: qwerty
  replicas: 10