apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: aziz-rs
  labels:
    app: myapp1
spec:
  template:
    metadata:
      name: azizapp
      labels:
        app: myapp1
    spec:
      containers:
        - name: httpd
          image: httpd
        - name: redis
          image: redis
  replicas: 1  
  selector:
    matchLabels:
      app: myapp1
