apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels: 
     app: myapp
     type: front-end
spec:
  template:
    metadata:
      name: aziztest
      labels: 
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          envFrom:
          - configMapRef:
              name: app-color
        
        - name: backend-container
          image: redis
          
  replicas: 3
  selector: 
    matchLabels:
      type: front-end