apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replica-controller
  labels: 
     app: myapp
     type: back-end
spec:
  template:
    metadata:
      name: aziztest
      labels: 
        app: myapp
        type: back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
        
        - name: backend-container
          image: redis
  replicas: 2